User.create(name: '石川界人', email: 'ishikawa@test.com', password: 'password')
User.create(name: '岡本信彦', email: 'okamoto@test.com', password: 'password')
User.create(name: '梶裕貴', email: 'kaji@test.com', password: 'password')
User.create(name: '花江夏樹', email: 'hanae@test.com', password: 'password')
User.create(name: '藤原啓治', email: 'hujiwara@test.com', password: 'password')